const env = import.meta.env || {};

export const REQUIRE_EMAIL_CONFIRMATION = env.VITE_REQUIRE_EMAIL_CONFIRMATION === 'true';

export const AUTH_COPY = Object.freeze({
  es: {
    accountCreated: 'Cuenta creada correctamente.',
    tribeReady: 'Ya puedes crear o unirte a una tribu.',
    signIn: 'Iniciar sesión',
    signUp: 'Registrarse',
    processing: 'Procesando…',
    show: 'Mostrar',
    hide: 'Ocultar',
    configTitle: 'Conexión pendiente',
    configBody: 'La interfaz está lista. Define VITE_SUPABASE_URL y VITE_SUPABASE_PUBLISHABLE_KEY para activar Auth.',
    login: {
      coordinate: 'W.E.A.F / ACCESO',
      context: 'Un solo acceso para tu perfil, tus criaturas y el espacio privado de tu tribu.',
      eyebrow: 'Bienvenido de vuelta',
      title: 'Ingresa a la forja',
      body: 'Continúa desde el último punto guardado.',
      created: 'Cuenta creada correctamente. Ya puedes entrar a W.E.A.F.',
      passwordUpdated: 'Contraseña actualizada. Ya puedes iniciar sesión.',
      email: 'Correo electrónico',
      password: 'Contraseña',
      recoveryQuestion: '¿Olvidaste tu contraseña?',
      recoveryHelp: 'Te enviaremos un enlace. Esta función depende de que SMTP esté disponible.',
      recoveryEmail: 'Correo de recuperación',
      sendLink: 'Enviar enlace',
      recoverySuccess: 'Si existe una cuenta asociada, recibirás instrucciones.',
      noAccount: '¿Aún no tienes cuenta?',
      createAccount: 'Crear cuenta',
    },
    register: {
      coordinate: 'W.E.A.F / NUEVO PERFIL',
      context: 'Empieza con tu identidad de juego y entra al espacio privado de tu tribu.',
      eyebrow: 'Tu primera coordenada',
      title: 'Crea tu cuenta',
      body: 'Necesitamos solo lo esencial para preparar tu espacio.',
      displayName: 'Nombre visible',
      displayNamePlaceholder: 'Cómo te conoce tu tribu',
      email: 'Correo electrónico',
      password: 'Contraseña',
      passwordHelp: 'Mínimo 8 caracteres.',
      gameQuestion: '¿Dónde juegas principalmente?',
      both: 'Ambos',
      combined: 'Perfil combinado',
      legalBefore: 'Acepto los',
      terms: 'Términos',
      legalAnd: 'y la',
      privacy: 'Política de privacidad',
      haveAccount: '¿Ya tienes cuenta?',
      confirmEyebrow: 'Un paso más',
      confirmTitle: 'Confirma tu correo',
      confirmBody: 'Enviamos un enlace de confirmación. Al abrirlo volverás a W.E.A.F para terminar tu perfil.',
    },
    captcha: {
      label: 'Verificación anti-bots',
      loading: 'Cargando desafío…',
      available: 'Completa la verificación para continuar.',
      verified: 'Verificación completada.',
      expired: 'La verificación expiró. Complétala otra vez.',
      error: 'No pudimos cargar la verificación. Inténtalo de nuevo.',
      sending: 'Validando acceso…',
      required: 'Completa la verificación anti-bots para continuar.',
      missingKey: 'La protección anti-bots no está configurada. El formulario permanece bloqueado.',
    },
    errors: {
      invalidCredentials: 'El correo o la contraseña no coinciden.',
      confirmEmail: 'Confirma tu correo antes de ingresar.',
      confirmEmailConfig: 'Supabase todavía exige confirmar el correo. Desactiva “Confirm email” para permitir el acceso directo.',
      signupUnavailable: 'No pudimos crear la cuenta. Revisa los datos e inténtalo de nuevo.',
      signupDisabled: 'El registro está deshabilitado temporalmente.',
      weakPassword: 'Usa una contraseña más segura.',
      rateLimit: 'Demasiados intentos. Espera unos minutos y vuelve a intentarlo.',
      generic: 'No pudimos completar la solicitud. Revisa tus datos e inténtalo de nuevo.',
    },
  },
  en: {
    accountCreated: 'Account created successfully.',
    tribeReady: 'You can now create or join a tribe.',
    signIn: 'Sign in',
    signUp: 'Sign up',
    processing: 'Processing…',
    show: 'Show',
    hide: 'Hide',
    configTitle: 'Connection pending',
    configBody: 'The interface is ready. Define VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to enable Auth.',
    login: {
      coordinate: 'W.E.A.F / ACCESS',
      context: 'One sign-in for your profile, creatures, and your tribe’s private workspace.',
      eyebrow: 'Welcome back',
      title: 'Enter the forge',
      body: 'Continue from your last saved point.',
      created: 'Account created successfully. You can now sign in to W.E.A.F.',
      passwordUpdated: 'Password updated. You can now sign in.',
      email: 'Email address',
      password: 'Password',
      recoveryQuestion: 'Forgot your password?',
      recoveryHelp: 'We will send a link. This feature depends on SMTP availability.',
      recoveryEmail: 'Recovery email',
      sendLink: 'Send link',
      recoverySuccess: 'If an associated account exists, you will receive instructions.',
      noAccount: 'Do not have an account yet?',
      createAccount: 'Create account',
    },
    register: {
      coordinate: 'W.E.A.F / NEW PROFILE',
      context: 'Start with your game identity and enter your tribe’s private workspace.',
      eyebrow: 'Your first coordinate',
      title: 'Create your account',
      body: 'We only need the essentials to prepare your workspace.',
      displayName: 'Display name',
      displayNamePlaceholder: 'How your tribe knows you',
      email: 'Email address',
      password: 'Password',
      passwordHelp: 'At least 8 characters.',
      gameQuestion: 'Where do you mainly play?',
      both: 'Both',
      combined: 'Combined profile',
      legalBefore: 'I accept the',
      terms: 'Terms',
      legalAnd: 'and the',
      privacy: 'Privacy Policy',
      haveAccount: 'Already have an account?',
      confirmEyebrow: 'One more step',
      confirmTitle: 'Confirm your email',
      confirmBody: 'We sent a confirmation link. Opening it will return you to W.E.A.F to finish your profile.',
    },
    captcha: {
      label: 'Anti-bot verification',
      loading: 'Loading challenge…',
      available: 'Complete the verification to continue.',
      verified: 'Verification complete.',
      expired: 'The verification expired. Complete it again.',
      error: 'We could not load the verification. Try again.',
      sending: 'Validating access…',
      required: 'Complete the anti-bot verification to continue.',
      missingKey: 'Anti-bot protection is not configured. The form remains blocked.',
    },
    errors: {
      invalidCredentials: 'The email or password does not match.',
      confirmEmail: 'Confirm your email before signing in.',
      confirmEmailConfig: 'Supabase still requires email confirmation. Disable “Confirm email” to allow direct access.',
      signupUnavailable: 'We could not create the account. Review the details and try again.',
      signupDisabled: 'Sign-up is temporarily disabled.',
      weakPassword: 'Use a stronger password.',
      rateLimit: 'Too many attempts. Wait a few minutes and try again.',
      generic: 'We could not complete the request. Review your details and try again.',
    },
  },
});

export function getAuthCopy(language = 'es') {
  return AUTH_COPY[language] || AUTH_COPY.es;
}

export function needsUnverifiedEmailNotice(user) {
  return !REQUIRE_EMAIL_CONFIRMATION || !user?.email_confirmed_at;
}
